"""Daily operations digest: one page per day, generated by the program from primary records.

It summarizes what the automated pipeline and the operator agent did that day — collection, research,
portfolio decisions, cloud execution, the daily review and governance changes — so a supervisor can
check direction without reading every model output. No model is called and nothing here is a judgment:
flags are fixed rules over counts and times. Days are Beijing calendar days.
"""
import copy
import json
from collections import Counter
from datetime import datetime, timedelta
from .storage import now, normalize_time, json_write
from .calendar import SH, local

BLOCKER_NAMES = {'RESEARCH_VETO': '研究否决', 'TREND_NOT_CONFIRMED': '趋势未确认', 'UNREAD_DOCUMENT': '关键资料未读',
                 'UNRESOLVED_EVENT': '事项待核验', 'CORPORATE_ACTION_UNVERIFIED': '公司行为待核验', 'SOURCE_GAP': '资料缺口',
                 'FINANCIAL_BASELINE_INCOMPLETE': '财务底稿不全', 'MARKET_CONTEXT_INCOMPLETE': '市场对照不全',
                 'MODEL_NOT_READY': '研究未完成', 'LOT_EXCEEDS_CAP': '单手超单股上限', 'UNSUPPORTED_BOARD': '板块不支持'}
RESEARCH_NAMES = {'WATCH': '可观察', 'REVIEW_REQUIRED': '需复核', 'INSUFFICIENT_DATA': '资料不足'}
PLAN_NAMES = {'PAPER_TRADE': '可开仓', 'NO_ENTRY': '不开仓', 'RISK_EXIT_ONLY': '只减仓', 'WAIT': '等待'}
ACTION_NAMES = {'ALLOW': '放行', 'HOLD': '保持', 'PAUSE': '暂停', 'REDUCE': '减仓', 'EXIT': '退出'}
STANCE_NAMES = {'LONG': '做多', 'WAIT': '观望'}
STATUS_NAMES = {'SUCCEEDED': '成功', 'DONE': '完成', 'FAILED': '失败', 'DEFERRED': '推迟', 'INTERRUPTED': '中断', 'PENDING': '排队',
                'RUNNING': '进行中', 'SKIPPED_CATCHUP': '合并跳过', 'MISSED': '错过', 'NOT_NEEDED': '无需分析', 'NONE': '无记录',
                'SENT': '已送达', 'SUPERSEDED': '被新版本替代', 'EXPIRED': '发送前过期', 'STALE': '云端拒收'}
CHECK_NAMES = {'CHECK_BUY_OUTSIDE_PLAN_BAND': '买入价超出计划区间', 'CHECK_BUY_WITH_PLAN_BLOCKERS': '计划有限制仍买入',
               'CHECK_BUY_WITHOUT_PORTFOLIO_ALLOW': '无组合授权仍买入', 'CHECK_BUY_WHILE_HALTED': '熔断期间买入',
               'CHECK_SELL_WITHOUT_REASON': '卖出无依据', 'CHECK_LATE_QUOTE_IN_REVIEW': '复盘用到晚到行情', 'CHECK_SYNC_STALE': '云端同步超时',
               'CHECK_OUTBOX_BACKLOG': '待发送策略积压', 'CHECK_MODEL_IDENTITY': '模型与固定配置不一致',
               'CHECK_RESEARCH_FAILURE_RATE': '研究失败率过高', 'CHECK_DISK_SPACE': '磁盘空间不足'}
DOCUMENT_NAMES = {'announcement': '公告', 'news': '新闻', 'report': '研报', 'financial_data': '财务数据', 'official_news': '官方新闻'}
NETWORK_ERRORS = ('nodename nor servname', 'Name or service not known', 'Temporary failure in name resolution',
                  'Network is unreachable', 'timed out', 'Connection refused', 'Connection reset')
ENGINE_KINDS = ('slot', 'dynamic_slot', 'global_slot', 'settle')  # cloud-side work; never runs on the research node


def day_window(day):
    start = datetime.fromisoformat(day).replace(tzinfo=SH)
    return normalize_time(start.isoformat()), normalize_time((start + timedelta(days=1)).isoformat())


def _rows(store, sql, args=()):
    try:
        return [dict(r) for r in store.db.execute(sql, args)]
    except Exception:
        return []  # a database from before the table existed


def _json(text, default=None):
    try:
        return json.loads(text) if text else default
    except (TypeError, ValueError):
        return default


def _hm(stamp):
    return local(stamp).strftime('%H:%M') if stamp else '—'


def _yuan(cents):
    return '—' if cents is None else f'{cents / 100:,.2f}'


def _blockers(codes, limit=3):
    names = Counter(BLOCKER_NAMES.get(str(c).split(':')[0], str(c).split(':')[0]) for c in codes or [])
    return '、'.join(n + (f'×{k}' if k > 1 else '') for n, k in names.most_common(limit)) or '—'


def _counts(counter, names=STATUS_NAMES):
    return '、'.join(f'{names.get(k, k)} {v}' for k, v in counter.items()) or '无'


def _names(config):
    return {i['symbol']: i.get('name') or i['symbol'] for i in config.get('watchlist', [])}


def jobs(store, a, b):
    rows = [r for r in _rows(store, 'SELECT id,kind,scheduled_at,started_at,finished_at,status,error FROM jobs WHERE scheduled_at>=? AND scheduled_at<? ORDER BY scheduled_at', (a, b))
            if r['kind'] not in ENGINE_KINDS and r['status'] not in ('MIGRATED', 'LOCAL_ONLY')]
    kinds = {}
    for r in rows:
        k = kinds.setdefault(r['kind'], Counter())
        k[r['status']] += 1
    longest = {}
    for r in rows:
        if r['started_at'] and r['finished_at']:
            minutes = round((datetime.fromisoformat(r['finished_at']) - datetime.fromisoformat(r['started_at'])).total_seconds() / 60)
            longest[r['kind']] = max(longest.get(r['kind'], 0), minutes)
    failed = [{'kind': r['kind'], 'at': r['scheduled_at'], 'status': r['status'], 'error': (r['error'] or '')[:120]}
              for r in rows if r['status'] in ('FAILED', 'DEFERRED', 'INTERRUPTED')]
    return {'by_kind': {k: dict(v) for k, v in sorted(kinds.items())}, 'longest_minutes': longest, 'failed': failed,
            'reconnect_recoveries': sum(1 for r in rows if r['id'].startswith('reconnect:'))}


def collection(store, a, b):
    from .presentation import SOURCE_NAMES
    rows = _rows(store, "SELECT source,status,detail FROM data_attempts WHERE checked_at>=? AND checked_at<? AND source NOT IN ('research_analysis','review_analysis')", (a, b))
    failed = [r for r in rows if r['status'] == 'FAILED']
    by_source = Counter(r['source'] for r in failed)
    network = sum(1 for r in failed if any(e in (r['detail'] or '') for e in NETWORK_ERRORS))
    documents = {r['kind']: r['n'] for r in _rows(store, 'SELECT kind,count(*) n FROM documents WHERE first_seen_at>=? AND first_seen_at<? GROUP BY kind', (a, b))}
    return {'attempts': len(rows), 'failed': len(failed), 'network_errors': network,
            'top_failures': [{'source': s, 'name': SOURCE_NAMES.get(s, s), 'count': n} for s, n in by_source.most_common(5)],
            'new_documents': documents}


def research(store, config, a, b):
    names = _names(config)
    studies = _rows(store, 'SELECT symbol,model_status FROM studies WHERE created_at>=? AND created_at<?', (a, b))
    renewed = _rows(store, "SELECT count(*) n FROM plan_events WHERE at>=? AND at<? AND reason LIKE 'RENEWED:%'", (a, b))
    failures = _rows(store, "SELECT count(*) n FROM data_attempts WHERE checked_at>=? AND checked_at<? AND source='research_analysis' AND status='FAILED'", (a, b))
    models = Counter()
    stocks = []
    for symbol, name in names.items():
        latest = _rows(store, "SELECT p.activated_at,p.payload_json,s.result_json,s.created_at study_at FROM plans p JOIN studies s ON s.id=p.study_id "
                       "WHERE p.symbol=? AND p.activated_at<? AND json_extract(p.payload_json,'$.kind')!='RISK_EXIT_ONLY' ORDER BY p.activated_at DESC,p.rowid DESC LIMIT 1", (symbol, b))
        before = _rows(store, "SELECT p.payload_json,s.result_json FROM plans p JOIN studies s ON s.id=p.study_id WHERE p.symbol=? AND p.activated_at<? "
                       "AND json_extract(p.payload_json,'$.kind')!='RISK_EXIT_ONLY' ORDER BY p.activated_at DESC,p.rowid DESC LIMIT 1", (symbol, a))
        if not latest:
            stocks.append({'symbol': symbol, 'name': name, 'research': None, 'plan': None, 'blockers': '—', 'source': '无计划', 'changed': False})
            continue
        row = latest[0]
        payload = _json(row['payload_json'], {})
        stock = ((_json(row['result_json'], {}) or {}).get('stocks') or [{}])[0]
        updated = row['activated_at'] >= a
        if updated:
            actual = (payload.get('model') or {}).get('actual_model')
            if actual:
                models[actual] += 1
        source = ('沿用 ' if payload.get('research_reuse') else '研究 ') + _hm(row['activated_at']) if updated else '沿用昨日计划'
        old = before[0] if before else None
        old_kind = (_json(old['payload_json'], {}) or {}).get('kind') if old else None
        old_action = (((_json(old['result_json'], {}) or {}).get('stocks') or [{}])[0]).get('action') if old else None
        stocks.append({'symbol': symbol, 'name': name, 'research': stock.get('action'), 'plan': payload.get('kind'),
                       'blockers': _blockers(payload.get('blockers')), 'source': source,
                       'changed': bool(old) and (old_kind != payload.get('kind') or old_action != stock.get('action'))})
    global_plans = []
    for r in _rows(store, 'SELECT g.symbol,g.created_at,g.payload_json FROM global_plans g WHERE g.created_at<? AND g.rowid=(SELECT rowid FROM global_plans x '
                   'WHERE x.symbol=g.symbol AND x.created_at<? ORDER BY x.created_at DESC,x.rowid DESC LIMIT 1) ORDER BY g.symbol', (b, b)):
        payload = _json(r['payload_json'], {})
        global_plans.append({'symbol': r['symbol'], 'stance': (payload.get('analysis') or {}).get('stance'), 'plan': payload.get('kind'),
                             'blockers': _blockers(payload.get('blockers')), 'updated': r['created_at'] >= a})
    cases = Counter(r['status'] for r in _rows(store, 'SELECT status FROM dynamic_cases WHERE created_at>=? AND created_at<?', (a, b)))
    return {'model_studies': Counter(s['model_status'] for s in studies), 'renewed': renewed[0]['n'] if renewed else 0,
            'analysis_failures': failures[0]['n'] if failures else 0, 'models': dict(models), 'stocks': stocks,
            'global': global_plans, 'dynamic_new_cases': dict(cases)}


def portfolio(store, a, b):
    runs = Counter(r['status'] for r in _rows(store, 'SELECT status FROM portfolio_runs WHERE started_at>=? AND started_at<?', (a, b)))
    made = _rows(store, 'SELECT created_at FROM portfolio_decisions WHERE created_at>=? AND created_at<? ORDER BY created_at', (a, b))
    def last_before(stamp):
        rows = _rows(store, 'SELECT created_at,payload_json FROM portfolio_decisions WHERE created_at<? ORDER BY created_at DESC,rowid DESC LIMIT 1', (stamp,))
        return (rows[0]['created_at'], _json(rows[0]['payload_json'], {})) if rows else (None, {})
    latest_at, latest = last_before(b)
    _, previous = last_before(a)
    decisions = latest.get('decisions') or []
    old = {d['key']: d for d in previous.get('decisions') or []}
    changes = []
    for d in decisions:
        o = old.get(d['key'])
        if o and (o.get('action') != d.get('action') or abs((o.get('target_bps') or 0) - (d.get('target_bps') or 0)) >= 100):
            changes.append({'key': d['key'], 'name': d.get('name') or d.get('symbol'), 'from': o.get('action'), 'to': d.get('action'),
                            'from_bps': o.get('target_bps'), 'to_bps': d.get('target_bps')})
    outbox = _rows(store, 'SELECT created_at,status,payload_json FROM cloud_outbox WHERE created_at>=? AND created_at<? ORDER BY created_at', (a, b))
    sizes = []
    for r in outbox:
        body = r['payload_json'] or ''
        marker = _json(body, {}) if body.startswith('{"pruned"') else {}
        sizes.append(marker.get('bytes') if marker.get('pruned') else len(body.encode()))
    sent = [r['created_at'] for r in outbox if r['status'] == 'SENT']
    prior = _rows(store, "SELECT max(created_at) t FROM cloud_outbox WHERE status='SENT' AND created_at<?", (a,))
    end = min(b, normalize_time(now()))
    points = ([prior[0]['t']] if prior and prior[0]['t'] else []) + sent + [end]
    gaps = [(datetime.fromisoformat(y) - datetime.fromisoformat(x)).total_seconds() / 3600 for x, y in zip(points, points[1:])]
    return {'runs': dict(runs), 'decisions_made': len(made), 'latest_at': latest_at,
            'latest_actions': dict(Counter(d.get('action') for d in decisions)),
            'latest_target_bps': sum(d.get('target_bps') or 0 for d in decisions),
            'latest_summary': (latest.get('summary') or '')[:160], 'changes': changes,
            'publications': dict(Counter(r['status'] for r in outbox)),
            'publication_bytes': {'max': max((s for s in sizes if s), default=None), 'last': sizes[-1] if sizes else None},
            'longest_gap_hours': round(max(gaps), 1) if gaps else None}


def execution(store, config, a, b):
    fills = {}
    for table, route in (('paper_fills', 'watchlist'), ('dynamic_fills', 'dynamic'), ('global_fills', 'global')):
        for r in _rows(store, f'SELECT symbol,side,qty,realized_cents FROM {table} WHERE occurred_at>=? AND occurred_at<?', (a, b)):
            f = fills.setdefault(route, {'buy': 0, 'sell': 0, 'realized_cents': 0, 'symbols': set()})
            f['buy' if r['side'] == 'BUY' else 'sell'] += 1
            f['realized_cents'] += r['realized_cents'] or 0
            f['symbols'].add(r['symbol'])
    for f in fills.values():
        f['symbols'] = sorted(f['symbols'])
    orders = Counter(r['status'] for t in ('paper_orders', 'dynamic_orders', 'global_orders')
                     for r in _rows(store, f'SELECT status FROM {t} WHERE created_at>=? AND created_at<?', (a, b)))
    def mark(stamp):
        rows = _rows(store, 'SELECT at,equity_cents,cash_cents,payload_json FROM equity_marks WHERE complete=1 AND at<? ORDER BY at DESC LIMIT 1', (stamp,))
        return rows[0] if rows else None
    start, end = mark(a), mark(b)
    positions = []
    if end:
        account = _json(end['payload_json'], {})
        equity = end['equity_cents'] or 1
        for group in ('positions', 'global_positions', 'dynamic_positions'):
            for symbol, p in (account.get(group) or {}).items():
                value = p.get('market_value_cents') or 0
                if p.get('qty'):
                    positions.append({'symbol': symbol, 'name': _names(config).get(symbol, symbol), 'group': group, 'value_cents': value,
                                      'weight_pct': round(value * 100 / equity, 2)})
        positions.sort(key=lambda p: -p['value_cents'])
    risk = _rows(store, 'SELECT payload_json FROM portfolio_risk ORDER BY updated_at DESC LIMIT 1')
    risk = _json(risk[0]['payload_json'], {}) if risk else {}
    return {'fills': fills, 'orders_created': dict(orders),
            'equity_start_cents': start['equity_cents'] if start else None, 'equity_end_cents': end['equity_cents'] if end else None,
            'cash_end_cents': end['cash_cents'] if end else None, 'marked_at': end['at'] if end else None,
            'positions': positions[:8], 'risk': {k: risk.get(k) for k in ('status', 'halted', 'drawdown_bps', 'peak_equity_cents') if k in risk}}


def review(store, a, b):
    rows = _rows(store, 'SELECT r.window_end,r.revision,r.model_status,r.payload_json FROM reviews r WHERE r.window_end>? AND r.window_end<=? '
                 'ORDER BY r.window_end DESC,r.revision DESC LIMIT 1', (a, b))
    if not rows:
        return {'status': 'NONE'}
    r = rows[0]
    payload = _json(r['payload_json'], {})
    checks = payload.get('consistency_checks') or []
    routing = Counter(x.get('to') for x in payload.get('routing') or [])
    return {'status': r['model_status'], 'window_end': r['window_end'], 'revision': r['revision'],
            'summary': ((payload.get('analysis') or {}).get('summary') or payload.get('analysis_error') or '')[:160],
            'checks_passed': sum(1 for c in checks if c.get('status') == 'PASS'), 'checks_total': len(checks),
            'checks_failed': [c.get('check') for c in checks if c.get('status') != 'PASS'], 'routing': dict(routing)}


def governance(store, a, b):
    changes = []
    log = store.root / 'workflow' / 'changes' / 'config-changes.jsonl'
    if log.exists():
        for line in log.read_text(encoding='utf-8').splitlines():
            e = _json(line, {})
            if e and a <= normalize_time(e.get('at', '1970-01-01T00:00:00+00:00')) < b:
                changes.append({k: e.get(k) for k in ('key', 'class', 'before', 'after', 'reason', 'approved_by', 'at')})
    proposals_new = _rows(store, 'SELECT id,kind,title,status,source FROM strategy_proposals WHERE created_at>=? AND created_at<?', (a, b))
    proposals_decided = _rows(store, 'SELECT id,title,status,decided_by FROM strategy_proposals WHERE decided_at>=? AND decided_at<?', (a, b))
    guidance = _rows(store, "SELECT id,route,status,approved_by FROM strategy_guidance WHERE (adopted_at>=? AND adopted_at<?) OR (retired_at>=? AND retired_at<?)", (a, b, a, b))
    issues_new = _rows(store, 'SELECT id,issue_key,category,symbol,title FROM engineering_issues WHERE first_seen_at>=? AND first_seen_at<?', (a, b))
    issues_seen = _rows(store, 'SELECT count(*) n FROM engineering_issues WHERE last_seen_at>=? AND last_seen_at<? AND first_seen_at<?', (a, b, a))
    issues_resolved = _rows(store, 'SELECT id,title,status FROM engineering_issues WHERE resolved_at>=? AND resolved_at<?', (a, b))
    builds = [(_json(r['payload_json'], {}) or {}).get('build_id') for r in _rows(store, 'SELECT payload_json FROM builds WHERE first_seen_at>=? AND first_seen_at<?', (a, b))]
    notes = []
    folder = store.root / 'workflow' / 'agent-notes'
    if folder.exists():
        for f in sorted(folder.glob('*')):
            if f.is_file() and a <= normalize_time(datetime.fromtimestamp(f.stat().st_mtime, SH).isoformat()) < b:
                notes.append(f.name)
    return {'config_changes': changes, 'proposals_new': proposals_new, 'proposals_decided': proposals_decided, 'guidance_changes': guidance,
            'issues_new': issues_new, 'issues_recurring': issues_seen[0]['n'] if issues_seen else 0, 'issues_resolved': issues_resolved,
            'new_builds': builds, 'agent_notes': notes}


def flags(d, config, today):
    """Fixed rules over the day's counts. They point at where to look; they are not conclusions."""
    out = []
    c = d['collection']
    if c['attempts'] >= 20 and c['failed'] * 5 >= c['attempts']:
        out.append(f"抓取失败率 {c['failed'] * 100 // c['attempts']}%（{c['failed']}/{c['attempts']}）" + (f"，其中网络类错误 {c['network_errors']} 次" if c['network_errors'] else ''))
    failed_cycles = [j for j in d['jobs']['failed'] if j['kind'] in ('cycle', 'collect', 'research')]
    if failed_cycles:
        out.append(f"资料研究任务未完成 {len(failed_cycles)} 次（最晚 {_hm(failed_cycles[-1]['at'])} 那轮）")
    r = d['research']
    studied = sum(r['model_studies'].values())
    if r['analysis_failures'] >= 3 or studied and r['model_studies'].get('FAILED', 0) * 10 >= studied * 3:
        out.append(f"研究模型调用失败 {max(r['analysis_failures'], r['model_studies'].get('FAILED', 0))} 次")
    pinned = config.get('model_name')
    other = [m for m in r['models'] if pinned and m != pinned]
    if other:
        out.append('研究实际使用了非固定模型：' + '、'.join(other))
    p = d['portfolio']
    if p['longest_gap_hours'] is not None and p['longest_gap_hours'] >= 3:
        out.append(f"组合策略发布最长间隔 {p['longest_gap_hours']} 小时（云端 12 小时收不到新策略就停止新买入）")
    if not p['publications'].get('SENT'):
        out.append('当天没有成功发布到云端的组合策略')
    review_hour = int(config.get('review_time', '19:30').split(':')[0])
    if d['review']['status'] not in ('SUCCEEDED', 'NOT_NEEDED') and (not today or local(now()).hour > review_hour):
        out.append('当天复盘未成功（' + STATUS_NAMES.get(d['review']['status'], str(d['review']['status'])) + '）')
    if d['review'].get('checks_failed'):
        out.append('复盘程序检查未通过：' + '、'.join(CHECK_NAMES.get(c, c) for c in d['review']['checks_failed']))
    if d['execution']['risk'].get('halted'):
        out.append('风控已触发暂停')
    g = d['governance']
    strategy_changes = [x['key'] for x in g['config_changes'] if x.get('class') == 'STRATEGY']
    if strategy_changes:
        out.append('策略类设置被修改：' + '、'.join(strategy_changes))
    if g['issues_new']:
        out.append(f"新增工程问题 {len(g['issues_new'])} 条")
    if d['jobs']['reconnect_recoveries']:
        out.append('服务曾中断或断网，恢复后补跑了任务')
    return out


# Neutral values used when a section cannot be built; the page then says so instead of implying nothing happened.
EMPTY = {'jobs': {'by_kind': {}, 'longest_minutes': {}, 'failed': [], 'reconnect_recoveries': 0},
         'collection': {'attempts': 0, 'failed': 0, 'network_errors': 0, 'top_failures': [], 'new_documents': {}},
         'research': {'model_studies': {}, 'renewed': 0, 'analysis_failures': 0, 'models': {}, 'stocks': [], 'global': [], 'dynamic_new_cases': {}},
         'portfolio': {'runs': {}, 'decisions_made': 0, 'latest_at': None, 'latest_actions': {}, 'latest_target_bps': 0, 'latest_summary': '',
                       'changes': [], 'publications': {}, 'publication_bytes': {'max': None, 'last': None}, 'longest_gap_hours': None},
         'execution': {'fills': {}, 'orders_created': {}, 'equity_start_cents': None, 'equity_end_cents': None, 'cash_end_cents': None,
                       'marked_at': None, 'positions': [], 'risk': {}},
         'review': {'status': 'NONE'},
         'governance': {'config_changes': [], 'proposals_new': [], 'proposals_decided': [], 'guidance_changes': [], 'issues_new': [],
                        'issues_recurring': 0, 'issues_resolved': [], 'new_builds': [], 'agent_notes': []}}
SECTION_TITLES = {'jobs': '任务运行', 'collection': '抓取', 'research': '研究', 'portfolio': '组合策略', 'execution': '云端执行',
                  'review': '复盘', 'governance': '调整与治理'}


def _safe(name, fn):
    try:
        return fn()
    except Exception as exc:
        return {**copy.deepcopy(EMPTY[name]), 'error': f'{type(exc).__name__}: {str(exc)[:160]}'}


def build(store, config, day):
    a, b = day_window(day)
    today = local(now()).date().isoformat() == day
    from . import __version__
    from .build import info
    d = {'day': day, 'generated_at': normalize_time(now()), 'window': {'from': a, 'to': b}, 'version': __version__,
         'build_id': info(config, store)['build_id']}
    for name, fn in (('jobs', lambda: jobs(store, a, b)), ('collection', lambda: collection(store, a, b)),
                     ('research', lambda: research(store, config, a, b)), ('portfolio', lambda: portfolio(store, a, b)),
                     ('execution', lambda: execution(store, config, a, b)), ('review', lambda: review(store, a, b)),
                     ('governance', lambda: governance(store, a, b))):
        d[name] = _safe(name, fn)
    d['research']['model_studies'] = dict(d['research']['model_studies'])
    d['flags'] = [f'日报的“{SECTION_TITLES[n]}”一节生成失败：{d[n]["error"]}' for n in SECTION_TITLES if d[n].get('error')]
    try:
        d['flags'] += flags(d, config, today)
    except Exception as exc:
        d['flags'].append(f'异常规则检查失败：{type(exc).__name__}: {str(exc)[:160]}')
    return d


def _failed(section):
    return [f"- 本节生成失败（{section['error']}），下列数值为空，不代表当天没有发生。", ''] if section.get('error') else []


def markdown(d):
    from .followups import JOB_NAMES
    L = [f"# 运行日报 {d['day']}（北京时间）", '',
         f"程序根据原始记录生成，不含模型判断。版本 {d['version']}，build {d['build_id']}，生成于 {local(d['generated_at']).strftime('%m-%d %H:%M')}。", '',
         '## 需要关注', '']
    L += [f'- {f}' for f in d['flags']] or ['- 无。']
    c = d['collection']
    L += ['', '## 抓取', ''] + _failed(c) + [f"- 采集尝试 {c['attempts']} 次，失败 {c['failed']} 次" + (f"（网络类错误 {c['network_errors']} 次）" if c['network_errors'] else '') + '。']
    if c['top_failures']:
        L.append('- 失败最多：' + '、'.join(f"{x['name']} {x['count']}" for x in c['top_failures']) + '。')
    L.append('- 新入库资料：' + _counts(dict(sorted(c['new_documents'].items())), DOCUMENT_NAMES) + '。')
    r = d['research']
    studies = r['model_studies']
    L += ['', '## 研究', ''] + _failed(r) + [f"- 模型研究 {sum(studies.values())} 次（成功 {studies.get('SUCCEEDED', 0)}），资料未变沿用结论 {r['renewed']} 次，研究生成失败 {r['analysis_failures']} 次。"
          + (' 实际模型：' + '、'.join(f'{m} {n}' for m, n in r['models'].items()) + '。' if r['models'] else ''), '',
          '| 股票 | 研究结论 | 计划 | 主要限制 | 来源 | 较前日 |', '|---|---|---|---|---|---|']
    for s in r['stocks']:
        L.append(f"| {s['name']} | {RESEARCH_NAMES.get(s['research'], s['research'] or '—')} | {PLAN_NAMES.get(s['plan'], s['plan'] or '—')} | "
                 f"{s['blockers']} | {s['source']} | {'变化' if s['changed'] else '—'} |")
    if r['global']:
        L += ['', '- 全球资产：' + '；'.join(f"{g['symbol']} {STANCE_NAMES.get(g['stance'], g['stance'] or '—')}、{PLAN_NAMES.get(g['plan'], g['plan'] or '—')}"
                                            + ('' if g['updated'] else '（当天未更新）') for g in r['global']) + '。']
    if r['dynamic_new_cases']:
        L.append('- 新闻发现的新候选：' + '、'.join(f'{k} {v}' for k, v in r['dynamic_new_cases'].items()) + '。')
    p = d['portfolio']
    L += ['', '## 组合策略', ''] + _failed(p) + [f"- 组合决策运行 {sum(p['runs'].values())} 次（{_counts(p['runs'])}），发布到云端：{_counts(p['publications'])}"
          + (f"；最长间隔 {p['longest_gap_hours']} 小时" if p['longest_gap_hours'] is not None else '') + '。']
    if p['publication_bytes']['last']:
        L.append(f"- 策略包大小：最后一次 {p['publication_bytes']['last'] / 1e6:.1f} MB，最大 {p['publication_bytes']['max'] / 1e6:.1f} MB。")
    if p['latest_at']:
        L.append(f"- 最新决策（{local(p['latest_at']).strftime('%m-%d %H:%M')}）：" + '、'.join(f"{ACTION_NAMES.get(k, k)} {v}" for k, v in p['latest_actions'].items())
                 + f"；目标总仓位 {p['latest_target_bps'] / 100:.1f}%。")
        L.append('- 与前一日最后决策相比：' + ('；'.join(f"{x['name']} {ACTION_NAMES.get(x['from'], x['from'])}→{ACTION_NAMES.get(x['to'], x['to'])}"
                                                   + (f"（目标 {(x['from_bps'] or 0) / 100:.1f}%→{(x['to_bps'] or 0) / 100:.1f}%）" if x['from_bps'] != x['to_bps'] else '')
                                                   for x in p['changes']) or '无变化') + '。')
        if p['latest_summary']:
            L.append(f"- 决策摘要：{p['latest_summary']}")
    e = d['execution']
    L += ['', '## 云端执行', ''] + _failed(e)
    if e['fills']:
        L += [f"- {route}：买入成交 {f['buy']} 笔、卖出 {f['sell']} 笔，已实现 {_yuan(f['realized_cents'])} 元（{'、'.join(f['symbols'])}）。" for route, f in e['fills'].items()]
    else:
        L.append('- 当天没有成交。')
    if e['equity_end_cents'] is not None:
        change = '' if e['equity_start_cents'] is None else f"，较前一日 {(e['equity_end_cents'] - e['equity_start_cents']) / 100:+,.2f} 元"
        L.append(f"- 净值 {_yuan(e['equity_end_cents'])} 元{change}；现金 {_yuan(e['cash_end_cents'])} 元（估值于 {_hm(e['marked_at'])}）。")
    if e['positions']:
        L.append('- 持仓：' + '、'.join(f"{x['name']} {x['weight_pct']}%" for x in e['positions']) + '。')
    if e['risk']:
        L.append('- 风控：' + json.dumps(e['risk'], ensure_ascii=False))
    v = d['review']
    L += ['', '## 复盘', ''] + _failed(v)
    if v['status'] == 'NONE':
        L.append('- 当天没有复盘记录。')
    else:
        L.append(f"- {_hm(v['window_end'])} 窗口复盘：{STATUS_NAMES.get(v['status'], v['status'])}；程序检查 {v['checks_passed']}/{v['checks_total']} 通过"
                 + (f"（未通过：{'、'.join(CHECK_NAMES.get(c, c) for c in v['checks_failed'])}）" if v['checks_failed'] else '') + '；发现去向：'
                 + ('、'.join(f"{'工程问题' if k == 'engineering_issue' else '提案草稿' if k == 'proposal_draft' else k} {n}" for k, n in v['routing'].items()) or '无') + '。')
        if v['summary']:
            L.append(f"- 结论：{v['summary']}")
    g = d['governance']
    L += ['', '## 调整与治理', ''] + _failed(g)
    L += [f"- 设置修改：{x['key']} {json.dumps(x['before'], ensure_ascii=False)}→{json.dumps(x['after'], ensure_ascii=False)}（{x['class']}，"
          + (f"批准人 {x['approved_by']}，" if x.get('approved_by') else '') + f"理由：{(x.get('reason') or '')[:60]}）" for x in g['config_changes']] or ['- 设置：无修改。']
    L.append(f"- 提案：新建 {len(g['proposals_new'])}，决策 {len(g['proposals_decided'])}"
             + ('（' + '；'.join(f"{x['id']} {x['title']} → {x['status']}，{x['decided_by']}" for x in g['proposals_decided']) + '）' if g['proposals_decided'] else '') + '。')
    if g['guidance_changes']:
        L.append('- 研究规则变化：' + '；'.join(f"{x['id']} {x['status']}（{x['approved_by']}）" for x in g['guidance_changes']) + '。')
    L.append(f"- 工程问题：新增 {len(g['issues_new'])}，再次出现 {g['issues_recurring']}，关闭 {len(g['issues_resolved'])}"
             + ('（新增：' + '；'.join(f"{x['title']}" for x in g['issues_new'][:5]) + '）' if g['issues_new'] else '') + '。')
    if g['new_builds']:
        L.append('- 新版本号：' + '、'.join(filter(None, g['new_builds'])) + '。')
    if g['agent_notes']:
        L.append('- 桌面 agent 笔记：' + '、'.join(g['agent_notes']) + '。')
    j = d['jobs']
    L += ['', '## 任务运行', ''] + _failed(j) + ['| 任务 | 结果 | 最长耗时（分钟） |', '|---|---|---|']
    L += [f"| {JOB_NAMES.get(k, k)} | {_counts(v)} | {j['longest_minutes'].get(k, '—')} |" for k, v in j['by_kind'].items()] or ['| — | 当天没有任务记录 | — |']
    return '\n'.join(L) + '\n'


def write(store, config, day=None):
    day = day or local(now()).date().isoformat()
    d = build(store, config, day)
    folder = store.root / 'workflow' / 'digests'
    json_write(folder / (day + '.json'), d)
    (folder / (day + '.md')).write_text(markdown(d), encoding='utf-8')
    return {'status': 'SUCCEEDED', 'day': day, 'report': str((folder / (day + '.md')).relative_to(store.root)), 'flags': d['flags']}


def rollup(store, config, since, until=None):
    """One page over several days for a supervisor's periodic check."""
    until = until or local(now()).date().isoformat()
    start, finish = datetime.fromisoformat(since).date(), datetime.fromisoformat(until).date()
    if finish < start:
        raise ValueError('结束日期早于开始日期')
    if (finish - start).days > 62:
        raise ValueError('汇总区间最长 62 天')
    days = []
    cursor = start
    while cursor <= finish:
        days.append(build(store, config, cursor.isoformat()))
        cursor += timedelta(days=1)
    L = [f'# 运行汇总 {since} 至 {until}（北京时间）', '', '程序根据原始记录生成，不含模型判断；每天的明细见 workflow/digests/<日期>.md。', '',
         '## 逐日概况', '', '| 日期 | 抓取失败 | 模型研究 / 沿用 / 失败 | 组合发布 / 最长间隔 | 成交笔数 | 净值（元） | 复盘 | 需关注 |', '|---|---|---|---|---|---|---|---|']
    for d in days:
        r, p, e = d['research'], d['portfolio'], d['execution']
        trades = sum(f['buy'] + f['sell'] for f in e['fills'].values())
        L.append(f"| {d['day']} | {d['collection']['failed']}/{d['collection']['attempts']} | {sum(r['model_studies'].values())} / {r['renewed']} / {r['analysis_failures']} | "
                 f"{p['publications'].get('SENT', 0)} / {p['longest_gap_hours'] if p['longest_gap_hours'] is not None else '—'}h | {trades} | {_yuan(e['equity_end_cents'])} | "
                 f"{STATUS_NAMES.get(d['review']['status'], d['review']['status'])} | {len(d['flags'])} |")
    L += ['', '## 需要关注（按日期）', '']
    L += [f"- {d['day']}：{f}" for d in days for f in d['flags']] or ['- 无。']
    L += ['', '## 调整与治理', '']
    events = []
    for d in days:
        g = d['governance']
        events += [f"- {d['day']} 设置 {x['key']}：{json.dumps(x['before'], ensure_ascii=False)}→{json.dumps(x['after'], ensure_ascii=False)}（{x['class']}，{x.get('approved_by') or '运行类'}）" for x in g['config_changes']]
        events += [f"- {d['day']} 新提案 {x['id']}：{x['title']}（{x['status']}）" for x in g['proposals_new']]
        events += [f"- {d['day']} 提案决策 {x['id']}：{x['title']} → {x['status']}（{x['decided_by']}）" for x in g['proposals_decided']]
        events += [f"- {d['day']} 研究规则 {x['id']} {x['status']}" for x in g['guidance_changes']]
        events += [f"- {d['day']} 新工程问题：{x['title']}" for x in g['issues_new']]
    L += events or ['- 区间内没有设置、提案、研究规则或工程问题的变化。']
    last = days[-1]
    changed = [s['name'] for d in days for s in d['research']['stocks'] if s['changed']]
    L += ['', '## 期末状态', '', f"- 研究结论有变化的股票：{'、'.join(dict.fromkeys(changed)) or '无'}。"]
    if last['portfolio']['latest_at']:
        L.append('- 最新组合决策：' + '、'.join(f"{ACTION_NAMES.get(k, k)} {v}" for k, v in last['portfolio']['latest_actions'].items())
                 + f"；目标总仓位 {last['portfolio']['latest_target_bps'] / 100:.1f}%。")
    if last['execution']['positions']:
        L.append('- 持仓：' + '、'.join(f"{x['name']} {x['weight_pct']}%" for x in last['execution']['positions']) + '。')
    text = '\n'.join(L) + '\n'
    folder = store.root / 'workflow' / 'digests'
    stem = f'rollup-{since}_{until}'
    json_write(folder / (stem + '.json'), {'since': since, 'until': until, 'days': days})
    (folder / (stem + '.md')).write_text(text, encoding='utf-8')
    return {'status': 'SUCCEEDED', 'report': str((folder / (stem + '.md')).relative_to(store.root)), 'days': len(days),
            'flags': sum(len(d['flags']) for d in days)}
