"""Daily operations digest: one page per day, generated by the program from primary records.

It summarizes what the automated pipeline and the operator agent did that day — collection, research,
portfolio decisions, cloud execution, the daily review and governance changes — so a supervisor can
check direction without reading every model output. No model is called and nothing here is a judgment:
flags are fixed rules over counts and times. Days are Beijing calendar days.

Research does not have to run on schedule (user decision, 2026-09-26): time the machine spent offline or
asleep is shown in its own section and is not flagged; the rules flag what went wrong while it was online.
"""
import copy
import json
from collections import Counter
from datetime import datetime, timedelta
from .storage import now, normalize_time, json_write
from .calendar import SH, local
from .connectivity import intervals, overlap_minutes, inside, offline_since, local_network_error

BLOCKER_NAMES = {'RESEARCH_VETO': '研究否决', 'TREND_NOT_CONFIRMED': '趋势未确认', 'UNREAD_DOCUMENT': '关键资料未读',
                 'UNRESOLVED_EVENT': '事项待核验', 'CORPORATE_ACTION_UNVERIFIED': '公司行为待核验', 'SOURCE_GAP': '资料缺口',
                 'FINANCIAL_BASELINE_INCOMPLETE': '财务底稿不全', 'MARKET_CONTEXT_INCOMPLETE': '市场对照不全',
                 'MODEL_NOT_READY': '研究未完成', 'LOT_EXCEEDS_CAP': '单手超单股上限', 'UNSUPPORTED_BOARD': '板块不支持'}
RESEARCH_NAMES = {'WATCH': '可观察', 'REVIEW_REQUIRED': '需复核', 'INSUFFICIENT_DATA': '资料不足'}
PLAN_NAMES = {'PAPER_TRADE': '可开仓', 'NO_ENTRY': '不开仓', 'RISK_EXIT_ONLY': '只减仓', 'WAIT': '等待'}
ACTION_NAMES = {'ALLOW': '放行', 'HOLD': '保持', 'PAUSE': '暂停', 'REDUCE': '减仓', 'EXIT': '退出'}
STANCE_NAMES = {'LONG': '做多', 'WAIT': '观望'}
STATUS_NAMES = {'SUCCEEDED': '成功', 'DONE': '完成', 'FAILED': '失败', 'DEFERRED': '推迟', 'INTERRUPTED': '中断', 'PENDING': '排队',
                'RUNNING': '进行中', 'SKIPPED_CATCHUP': '合并跳过', 'MISSED': '错过', 'NOT_NEEDED': '无需分析', 'NONE': '无记录',
                'SENT': '已送达', 'SUPERSEDED': '被新版本替代', 'EXPIRED': '发送前过期', 'STALE': '云端拒收', 'OFFLINE': '断网停止'}
CHECK_NAMES = {'CHECK_BUY_OUTSIDE_PLAN_BAND': '买入价超出计划区间', 'CHECK_BUY_WITH_PLAN_BLOCKERS': '计划有限制仍买入',
               'CHECK_BUY_WITHOUT_PORTFOLIO_ALLOW': '无组合授权仍买入', 'CHECK_BUY_WHILE_HALTED': '熔断期间买入',
               'CHECK_SELL_WITHOUT_REASON': '卖出无依据', 'CHECK_LATE_QUOTE_IN_REVIEW': '复盘用到晚到行情', 'CHECK_SYNC_STALE': '云端同步超时',
               'CHECK_OUTBOX_BACKLOG': '待发送策略积压', 'CHECK_MODEL_IDENTITY': '模型与固定配置不一致',
               'CHECK_RESEARCH_FAILURE_RATE': '研究失败率过高', 'CHECK_DISK_SPACE': '磁盘空间不足'}
DOCUMENT_NAMES = {'announcement': '公告', 'announcement_metadata': '公告目录', 'company_report': '公司报告', 'report': '研报',
                  'financial_data': '财务数据', 'news': '新闻', 'news_brief': '新闻摘要', 'news_index': '新闻索引', 'official_news': '官方新闻'}
JOB_KIND_NAMES = {'dynamic_cycle': '动态新闻', 'global_research': '全球资产研究', 'portfolio_strategy': '组合决策'}
LONG_CYCLE_MINUTES = 120  # a collection this long keeps portfolio decisions waiting
NETWORK_ERRORS = ('nodename nor servname', 'Name or service not known', 'Temporary failure in name resolution',
                  'Network is unreachable', 'timed out', 'Connection refused', 'Connection reset')
ENGINE_KINDS = ('slot', 'dynamic_slot', 'global_slot', 'settle')  # cloud-side work; never runs on the research node


def day_window(day):
    start = datetime.fromisoformat(day).replace(tzinfo=SH)
    return normalize_time(start.isoformat()), normalize_time((start + timedelta(days=1)).isoformat())


def _rows(store, sql, args=()):
    try:
        return [dict(r) for r in store.db.execute(sql, args)]
    except Exception:
        return []  # a database from before the table existed


def _json(text, default=None):
    try:
        return json.loads(text) if text else default
    except (TypeError, ValueError):
        return default


def _hm(stamp):
    return local(stamp).strftime('%H:%M') if stamp else '—'


def _md(stamp):
    return local(stamp).strftime('%m-%d %H:%M') if stamp else '—'


def _span(s, b=None):
    """HH:MM–HH:MM inside one day; the day's end reads 24:00."""
    return _hm(s['from']) + '–' + ('24:00' if b and s['to'] == b else _hm(s['to'])) + ('（进行中）' if s.get('ongoing') else '')


def _hours(minutes):
    return round((minutes or 0) / 60, 1)


def _online_minutes(store, start, end):
    total = (datetime.fromisoformat(end) - datetime.fromisoformat(start)).total_seconds() / 60
    return total - overlap_minutes(start, end, intervals(store.root, start, end))


def _state(row):
    """Jobs stopped because the machine went offline are expected at this stage, not failures."""
    return 'OFFLINE' if row['status'] == 'DEFERRED' and (row.get('error') or '').startswith('OFFLINE:') else row['status']


def _yuan(cents):
    return '—' if cents is None else f'{cents / 100:,.2f}'


def _blockers(codes, limit=3):
    names = Counter(BLOCKER_NAMES.get(str(c).split(':')[0], str(c).split(':')[0]) for c in codes or [])
    return '、'.join(n + (f'×{k}' if k > 1 else '') for n, k in names.most_common(limit)) or '—'


def _counts(counter, names=STATUS_NAMES):
    return '、'.join(f'{names.get(k, k)} {v}' for k, v in counter.items()) or '无'


def _names(config):
    return {i['symbol']: i.get('name') or i['symbol'] for i in config.get('watchlist', [])}


def availability(store, a, b):
    """Periods this machine was offline or its scheduler did not run (asleep, or the service stopped)."""
    end = min(b, normalize_time(now()))
    spans = intervals(store.root, a, b)
    current = offline_since(store)
    if current and current < end and not any(s['kind'] == 'offline' and s['to'] >= end for s in spans):
        start = max(current, a)
        spans.append({'kind': 'offline', 'from': start, 'to': end, 'cause': 'NETWORK', 'ongoing': True,
                      'minutes': round((datetime.fromisoformat(end) - datetime.fromisoformat(start)).total_seconds() / 60)})
    offline = [s for s in spans if s['kind'] == 'offline']
    paused = [s for s in spans if s['kind'] == 'pause']
    return {'spans': sorted(spans, key=lambda s: s['from']), 'offline_minutes': round(overlap_minutes(a, end, offline)),
            'paused_minutes': round(overlap_minutes(a, end, paused)), 'away_minutes': round(overlap_minutes(a, end, spans))}


def jobs(store, a, b):
    rows = [r for r in _rows(store, 'SELECT id,kind,scheduled_at,started_at,finished_at,status,error FROM jobs WHERE scheduled_at>=? AND scheduled_at<? ORDER BY scheduled_at', (a, b))
            if r['kind'] not in ENGINE_KINDS and r['status'] not in ('MIGRATED', 'LOCAL_ONLY')]
    kinds = {}
    for r in rows:
        r['state'] = _state(r)
        kinds.setdefault(r['kind'], Counter())[r['state']] += 1
    longest = {}
    long_cycles = []
    for r in rows:
        if r['started_at'] and r['finished_at']:
            minutes = round((datetime.fromisoformat(r['finished_at']) - datetime.fromisoformat(r['started_at'])).total_seconds() / 60)
            longest[r['kind']] = max(longest.get(r['kind'], 0), minutes)
            if r['kind'] in ('cycle', 'collect', 'research') and minutes >= LONG_CYCLE_MINUTES:
                online = round(_online_minutes(store, r['started_at'], r['finished_at']))
                if online >= LONG_CYCLE_MINUTES:
                    long_cycles.append({'kind': r['kind'], 'at': r['scheduled_at'], 'minutes': minutes, 'online_minutes': online})
    failed = [{'kind': r['kind'], 'at': r['scheduled_at'], 'status': r['status'], 'error': (r['error'] or '')[:120]}
              for r in rows if r['state'] in ('FAILED', 'DEFERRED', 'INTERRUPTED')]
    return {'by_kind': {k: dict(v) for k, v in sorted(kinds.items())}, 'longest_minutes': longest, 'failed': failed,
            'offline_stopped': [{'kind': r['kind'], 'at': r['scheduled_at']} for r in rows if r['state'] == 'OFFLINE'],
            'long_cycles': long_cycles, 'reconnect_recoveries': sum(1 for r in rows if r['id'].startswith('reconnect:'))}


def collection(store, a, b, spans=()):
    from .presentation import SOURCE_NAMES
    rows = _rows(store, "SELECT source,status,detail,checked_at FROM data_attempts WHERE checked_at>=? AND checked_at<? AND source NOT IN ('research_analysis','review_analysis')", (a, b))
    failed = [r for r in rows if r['status'] == 'FAILED']
    online_failed = [r for r in failed if not inside(r['checked_at'], spans)]
    by_source = Counter(r['source'] for r in online_failed)
    network = sum(1 for r in failed if any(e in (r['detail'] or '') for e in NETWORK_ERRORS))
    documents = {r['kind']: r['n'] for r in _rows(store, 'SELECT kind,count(*) n FROM documents WHERE first_seen_at>=? AND first_seen_at<? GROUP BY kind', (a, b))}
    return {'attempts': len(rows), 'failed': len(failed), 'network_errors': network,
            'attempts_offline': sum(1 for r in rows if inside(r['checked_at'], spans)), 'failed_offline': len(failed) - len(online_failed),
            'top_failures': [{'source': s, 'name': SOURCE_NAMES.get(s, s), 'count': n} for s, n in by_source.most_common(5)],
            'new_documents': documents}


def research(store, config, a, b, spans=()):
    names = _names(config)
    studies = _rows(store, 'SELECT symbol,model_status,created_at FROM studies WHERE created_at>=? AND created_at<?', (a, b))
    renewed = _rows(store, "SELECT count(*) n FROM plan_events WHERE at>=? AND at<? AND reason LIKE 'RENEWED:%'", (a, b))
    failures = _rows(store, "SELECT checked_at FROM data_attempts WHERE checked_at>=? AND checked_at<? AND source='research_analysis' AND status='FAILED'", (a, b))
    models = Counter()
    stocks = []
    for symbol, name in names.items():
        latest = _rows(store, "SELECT p.activated_at,p.payload_json,s.result_json,s.created_at study_at FROM plans p JOIN studies s ON s.id=p.study_id "
                       "WHERE p.symbol=? AND p.activated_at<? AND json_extract(p.payload_json,'$.kind')!='RISK_EXIT_ONLY' ORDER BY p.activated_at DESC,p.rowid DESC LIMIT 1", (symbol, b))
        before = _rows(store, "SELECT p.payload_json,s.result_json FROM plans p JOIN studies s ON s.id=p.study_id WHERE p.symbol=? AND p.activated_at<? "
                       "AND json_extract(p.payload_json,'$.kind')!='RISK_EXIT_ONLY' ORDER BY p.activated_at DESC,p.rowid DESC LIMIT 1", (symbol, a))
        if not latest:
            stocks.append({'symbol': symbol, 'name': name, 'research': None, 'plan': None, 'blockers': '—', 'source': '无计划', 'changed': False})
            continue
        row = latest[0]
        payload = _json(row['payload_json'], {})
        stock = ((_json(row['result_json'], {}) or {}).get('stocks') or [{}])[0]
        updated = row['activated_at'] >= a
        if updated:
            actual = (payload.get('model') or {}).get('actual_model')
            if actual:
                models[actual] += 1
        source = ('沿用 ' if payload.get('research_reuse') else '研究 ') + _hm(row['activated_at']) if updated else '沿用昨日计划'
        old = before[0] if before else None
        old_kind = (_json(old['payload_json'], {}) or {}).get('kind') if old else None
        old_action = (((_json(old['result_json'], {}) or {}).get('stocks') or [{}])[0]).get('action') if old else None
        stocks.append({'symbol': symbol, 'name': name, 'research': stock.get('action'), 'plan': payload.get('kind'),
                       'blockers': _blockers(payload.get('blockers')), 'source': source,
                       'changed': bool(old) and (old_kind != payload.get('kind') or old_action != stock.get('action'))})
    global_plans = []
    for r in _rows(store, 'SELECT g.symbol,g.created_at,g.payload_json FROM global_plans g WHERE g.created_at<? AND g.rowid=(SELECT rowid FROM global_plans x '
                   'WHERE x.symbol=g.symbol AND x.created_at<? ORDER BY x.created_at DESC,x.rowid DESC LIMIT 1) ORDER BY g.symbol', (b, b)):
        payload = _json(r['payload_json'], {})
        global_plans.append({'symbol': r['symbol'], 'stance': (payload.get('analysis') or {}).get('stance'), 'plan': payload.get('kind'),
                             'blockers': _blockers(payload.get('blockers')), 'updated': r['created_at'] >= a})
    cases = Counter(r['status'] for r in _rows(store, 'SELECT status FROM dynamic_cases WHERE created_at>=? AND created_at<?', (a, b)))
    return {'model_studies': Counter(s['model_status'] for s in studies), 'renewed': renewed[0]['n'] if renewed else 0,
            'studies_offline': sum(1 for s in studies if inside(s['created_at'], spans)),
            'unsuccessful_offline': sum(1 for s in studies if s['model_status'] != 'SUCCEEDED' and inside(s['created_at'], spans)),
            'analysis_failures': len(failures), 'analysis_failures_offline': sum(1 for f in failures if inside(f['checked_at'], spans)),
            'models': dict(models), 'stocks': stocks, 'global': global_plans, 'dynamic_new_cases': dict(cases)}


def portfolio(store, a, b):
    runs = Counter(r['status'] for r in _rows(store, 'SELECT status FROM portfolio_runs WHERE started_at>=? AND started_at<?', (a, b)))
    made = _rows(store, 'SELECT created_at FROM portfolio_decisions WHERE created_at>=? AND created_at<? ORDER BY created_at', (a, b))
    def last_before(stamp):
        rows = _rows(store, 'SELECT created_at,payload_json FROM portfolio_decisions WHERE created_at<? ORDER BY created_at DESC,rowid DESC LIMIT 1', (stamp,))
        return (rows[0]['created_at'], _json(rows[0]['payload_json'], {})) if rows else (None, {})
    latest_at, latest = last_before(b)
    _, previous = last_before(a)
    decisions = latest.get('decisions') or []
    old = {d['key']: d for d in previous.get('decisions') or []}
    changes = []
    for d in decisions:
        o = old.get(d['key'])
        if o and (o.get('action') != d.get('action') or abs((o.get('target_bps') or 0) - (d.get('target_bps') or 0)) >= 100):
            changes.append({'key': d['key'], 'name': d.get('name') or d.get('symbol'), 'from': o.get('action'), 'to': d.get('action'),
                            'from_bps': o.get('target_bps'), 'to_bps': d.get('target_bps')})
    outbox = _rows(store, 'SELECT created_at,status,payload_json FROM cloud_outbox WHERE created_at>=? AND created_at<? ORDER BY created_at', (a, b))
    sizes = []
    for r in outbox:
        body = r['payload_json'] or ''
        marker = _json(body, {}) if body.startswith('{"pruned"') else {}
        sizes.append(marker.get('bytes') if marker.get('pruned') else len(body.encode()))
    sent = [r['created_at'] for r in outbox if r['status'] == 'SENT']
    prior = _rows(store, "SELECT max(created_at) t FROM cloud_outbox WHERE status='SENT' AND created_at<?", (a,))
    end = min(b, normalize_time(now()))
    points = ([prior[0]['t']] if prior and prior[0]['t'] else []) + sent + [end]
    current = offline_since(store)
    gaps = []
    for x, y in zip(points, points[1:]):
        if y <= x:
            continue
        spans = intervals(store.root, x, y) + ([{'from': max(current, x), 'to': y}] if current and current < y else [])
        hours = (datetime.fromisoformat(y) - datetime.fromisoformat(x)).total_seconds() / 3600
        away = overlap_minutes(x, y, spans) / 60
        gaps.append({'from': x, 'to': y, 'hours': round(hours, 1), 'away_hours': round(away, 1), 'online_hours': round(hours - away, 1)})
    job_rows = [{**r, 'state': _state(r)} for r in _rows(store, "SELECT status,error FROM jobs WHERE kind='portfolio_strategy' AND scheduled_at>=? AND scheduled_at<?", (a, b))]
    reasons = Counter('同步占用' if (r['error'] or '').startswith('RuntimeError: BUSY') else '断网' if local_network_error(r['error']) else '其他'
                      for r in job_rows if r['state'] == 'FAILED')
    longest = max(gaps, key=lambda g: g['hours'], default=None)
    return {'runs': dict(runs), 'decisions_made': len(made), 'latest_at': latest_at,
            'jobs': dict(Counter(r['state'] for r in job_rows)), 'job_failure_reasons': dict(reasons),
            'longest_gap': longest, 'longest_online_gap': max(gaps, key=lambda g: g['online_hours'], default=None),
            'latest_actions': dict(Counter(d.get('action') for d in decisions)),
            'latest_target_bps': sum(d.get('target_bps') or 0 for d in decisions),
            'latest_summary': (latest.get('summary') or '')[:160], 'changes': changes,
            'publications': dict(Counter(r['status'] for r in outbox)),
            'publication_bytes': {'max': max((s for s in sizes if s), default=None), 'last': sizes[-1] if sizes else None},
            'longest_gap_hours': longest['hours'] if longest else None}


def execution(store, config, a, b):
    fills = {}
    for table, route in (('paper_fills', 'watchlist'), ('dynamic_fills', 'dynamic'), ('global_fills', 'global')):
        for r in _rows(store, f'SELECT symbol,side,qty,realized_cents FROM {table} WHERE occurred_at>=? AND occurred_at<?', (a, b)):
            f = fills.setdefault(route, {'buy': 0, 'sell': 0, 'realized_cents': 0, 'symbols': set()})
            f['buy' if r['side'] == 'BUY' else 'sell'] += 1
            f['realized_cents'] += r['realized_cents'] or 0
            f['symbols'].add(r['symbol'])
    for f in fills.values():
        f['symbols'] = sorted(f['symbols'])
    orders = Counter(r['status'] for t in ('paper_orders', 'dynamic_orders', 'global_orders')
                     for r in _rows(store, f'SELECT status FROM {t} WHERE created_at>=? AND created_at<?', (a, b)))
    def mark(stamp):
        rows = _rows(store, 'SELECT at,equity_cents,cash_cents,payload_json FROM equity_marks WHERE complete=1 AND at<? ORDER BY at DESC LIMIT 1', (stamp,))
        return rows[0] if rows else None
    start, end = mark(a), mark(b)
    positions = []
    if end:
        account = _json(end['payload_json'], {})
        equity = end['equity_cents'] or 1
        for group in ('positions', 'global_positions', 'dynamic_positions'):
            for symbol, p in (account.get(group) or {}).items():
                value = p.get('market_value_cents') or 0
                if p.get('qty'):
                    positions.append({'symbol': symbol, 'name': _names(config).get(symbol, symbol), 'group': group, 'value_cents': value,
                                      'weight_pct': round(value * 100 / equity, 2)})
        positions.sort(key=lambda p: -p['value_cents'])
    risk = _rows(store, 'SELECT payload_json FROM portfolio_risk ORDER BY updated_at DESC LIMIT 1')
    risk = _json(risk[0]['payload_json'], {}) if risk else {}
    from .dividends import parse, KIND
    dividends = []
    for r in _rows(store, 'SELECT reference,amount_cents FROM paper_flows WHERE kind=? AND created_at>=? AND created_at<? ORDER BY created_at', (KIND, a, b)):
        d = parse(r['reference'])
        if d:
            dividends.append({'symbol': d['symbol'], 'name': _names(config).get(d['symbol'], d['symbol']), 'ex_date': d['ex_date'],
                              'qty': d['qty'], 'cash_per_share': format(d['cash'], 'f'), 'amount_cents': r['amount_cents']})
    return {'fills': fills, 'orders_created': dict(orders), 'dividends': dividends,
            'equity_start_cents': start['equity_cents'] if start else None, 'equity_end_cents': end['equity_cents'] if end else None,
            'cash_end_cents': end['cash_cents'] if end else None, 'marked_at': end['at'] if end else None,
            'positions': positions[:8], 'risk': {k: risk.get(k) for k in ('status', 'halted', 'drawdown_bps', 'peak_equity_cents') if k in risk}}


def quotes(store, a, b):
    """Quote-source outages recorded by the executing node (mirrored to the research node with the ledger)."""
    from .quote_health import summary
    return summary(store, a, b)


def extras_errors(store):
    """On the research node: outage records or notice answers that failed to come over with the ledger."""
    from .cloud_runtime import value
    return {k: e for k in ('quote_health', 'notices') if (e := value(store, 'extras_error_' + k))}


def review(store, a, b):
    rows = _rows(store, 'SELECT r.window_end,r.revision,r.model_status,r.payload_json FROM reviews r WHERE r.window_end>? AND r.window_end<=? '
                 'ORDER BY r.window_end DESC,r.revision DESC LIMIT 1', (a, b))
    if not rows:
        return {'status': 'NONE'}
    r = rows[0]
    payload = _json(r['payload_json'], {})
    checks = payload.get('consistency_checks') or []
    routing = Counter(x.get('to') for x in payload.get('routing') or [])
    return {'status': r['model_status'], 'window_end': r['window_end'], 'revision': r['revision'],
            'summary': ((payload.get('analysis') or {}).get('summary') or payload.get('analysis_error') or '')[:160],
            'checks_passed': sum(1 for c in checks if c.get('status') == 'PASS'), 'checks_total': len(checks),
            'checks_not_applicable': sum(c.get('status') == 'NOT_APPLICABLE' for c in checks),
            'checks_failed': [c.get('check') for c in checks if c.get('status') in ('FAIL','INSUFFICIENT','ERROR')], 'routing': dict(routing)}


def governance(store, a, b):
    from .selfcheck import status as selfcheck_status
    changes = []
    log = store.root / 'workflow' / 'changes' / 'config-changes.jsonl'
    if log.exists():
        for line in log.read_text(encoding='utf-8').splitlines():
            e = _json(line, {})
            if e and a <= normalize_time(e.get('at', '1970-01-01T00:00:00+00:00')) < b:
                changes.append({k: e.get(k) for k in ('key', 'class', 'before', 'after', 'reason', 'approved_by', 'at')})
    proposals_new = _rows(store, 'SELECT id,kind,title,status,source FROM strategy_proposals WHERE created_at>=? AND created_at<?', (a, b))
    proposals_decided = [{'id': r['id'], 'title': r['title'], 'status': r['status'], 'decided_by': r['decided_by'],
                          'replaced_by': (_json(r['payload_json'], {}) or {}).get('superseded_by') if r['status'] == 'SUPERSEDED' else None}
                         for r in _rows(store, 'SELECT id,title,status,decided_by,payload_json FROM strategy_proposals WHERE decided_at>=? AND decided_at<?', (a, b))]
    guidance = _rows(store, "SELECT id,route,status,approved_by FROM strategy_guidance WHERE (adopted_at>=? AND adopted_at<?) OR (retired_at>=? AND retired_at<?)", (a, b, a, b))
    issues_new = _rows(store, 'SELECT id,issue_key,category,symbol,title FROM engineering_issues WHERE first_seen_at>=? AND first_seen_at<?', (a, b))
    issues_seen = _rows(store, 'SELECT count(*) n FROM engineering_issues WHERE last_seen_at>=? AND last_seen_at<? AND first_seen_at<?', (a, b, a))
    issues_resolved = _rows(store, 'SELECT id,title,status FROM engineering_issues WHERE resolved_at>=? AND resolved_at<?', (a, b))
    issues_retitled = [{'id': r['id'], 'from': t.get('from'), 'to': t.get('to')}
                       for r in _rows(store, "SELECT id,payload_json FROM engineering_issues WHERE payload_json LIKE '%\"titles\"%'")
                       for t in (_json(r['payload_json'], {}) or {}).get('titles', []) if a <= t.get('at', '') < b]
    builds = [(_json(r['payload_json'], {}) or {}).get('build_id') for r in _rows(store, 'SELECT payload_json FROM builds WHERE first_seen_at>=? AND first_seen_at<?', (a, b))]
    notes = []
    folder = store.root / 'workflow' / 'agent-notes'
    if folder.exists():
        for f in sorted(folder.glob('*')):
            if f.is_file() and a <= normalize_time(datetime.fromtimestamp(f.stat().st_mtime, SH).isoformat()) < b:
                notes.append(f.name)
    return {'config_changes': changes, 'proposals_new': proposals_new, 'proposals_decided': proposals_decided, 'guidance_changes': guidance,
            'selfcheck': selfcheck_status(store).get('last'),
            'issues_new': issues_new, 'issues_recurring': issues_seen[0]['n'] if issues_seen else 0, 'issues_resolved': issues_resolved,
            'issues_retitled': issues_retitled,
            'new_builds': builds, 'agent_notes': notes}


def _decision(x):
    if x['status'] == 'SUPERSEDED':
        return f"被新版 {x.get('replaced_by') or '—'} 替代"
    return f"{x['status']}（{x['decided_by'] or '代理整理'}）"


def flags(d, config, today):
    """Fixed rules over the day's counts. They point at where to look; they are not conclusions.
    Offline and paused time is excluded: at this stage research may wait until the machine is back."""
    out = []
    spans = d['availability']['spans']
    c = d['collection']
    attempts, failed = c['attempts'] - c['attempts_offline'], c['failed'] - c['failed_offline']
    if attempts >= 20 and failed * 5 >= attempts:
        out.append(f"联网期间抓取失败率 {failed * 100 // attempts}%（{failed}/{attempts}）")
    failed_cycles = [j for j in d['jobs']['failed'] if j['kind'] in ('cycle', 'collect', 'research')]
    if failed_cycles:
        out.append(f"资料研究任务未完成 {len(failed_cycles)} 次（最晚 {_hm(failed_cycles[-1]['at'])} 那轮）")
    long_cycles = d['jobs'].get('long_cycles') or []
    if long_cycles:
        worst = max(long_cycles, key=lambda j: j['online_minutes'])
        out.append(f"资料研究在联网状态下耗时 {worst['online_minutes']} 分钟（{_hm(worst['at'])} 那轮），超过 {LONG_CYCLE_MINUTES // 60} 小时；运行期间组合决策排队")
    r = d['research']
    studied = sum(r['model_studies'].values()) - r['studies_offline']
    unsuccessful = studied + r['studies_offline'] - r['model_studies'].get('SUCCEEDED', 0) - r['unsuccessful_offline']
    if unsuccessful >= 5 and unsuccessful * 10 >= studied:
        out.append(f"联网期间研究模型调用失败 {unsuccessful} 次（占 {unsuccessful * 100 // max(studied, 1)}%）")
    pinned = config.get('model_name')
    other = [m for m in r['models'] if pinned and m != pinned]
    if other:
        out.append('研究实际使用了非固定模型：' + '、'.join(other))
    p = d['portfolio']
    longest, online = p.get('longest_gap'), p.get('longest_online_gap')
    halted = longest if longest and longest['hours'] >= 12 else None
    if halted:
        out.append(f"组合策略 {halted['hours']} 小时没有发布（{_md(halted['from'])} 至 {_md(halted['to'])}"
                   + (f"，其中离线或停顿 {halted['away_hours']} 小时" if halted['away_hours'] else '') + '），超过 12 小时，云端停止了新买入')
    if online and online['online_hours'] >= 3 and not (halted and halted['from'] == online['from']):
        out.append(f"组合策略在联网状态下 {online['online_hours']} 小时没有发布（{_md(online['from'])} 至 {_md(online['to'])}）")
    if not p['publications'].get('SENT'):
        away = d['availability']['away_minutes']
        out.append('当天没有成功发布到云端的组合策略' + (f"（当天离线或停顿 {_hours(away)} 小时）" if away else ''))
    review_time = config.get('review_time', '19:30')
    review_at = normalize_time(f"{d['day']}T{review_time}:00+08:00")
    if d['review']['status'] not in ('SUCCEEDED', 'NOT_NEEDED') and (not today or normalize_time(now()) >= review_at):
        if inside(review_at, spans):
            out.append('当天复盘未完成：复盘时间本机离线或停顿，联网后补做')
        else:
            out.append('当天复盘未成功（' + STATUS_NAMES.get(d['review']['status'], str(d['review']['status'])) + '）')
    if d['review'].get('checks_failed'):
        out.append('复盘程序检查未通过：' + '、'.join(CHECK_NAMES.get(c, c) for c in d['review']['checks_failed']))
    if d['execution']['risk'].get('halted'):
        out.append('风控已触发暂停')
    q = d.get('quotes') or EMPTY['quotes']
    if q['held_minutes'] >= 5:
        out.append(f"持仓股票有 {q['held_minutes']} 分钟两个行情接口都没有可用报价，期间无法按止损卖出")
    elif q['minutes']['NO_QUOTE'] >= 30:
        out.append(f"自选股累计 {q['minutes']['NO_QUOTE']} 分钟没有可用报价，期间不会买入")
    for x in q['breaches']:
        out.append(f"行情中断时 {x['symbol']} 的分时最低价 {_yuan(x['low_cents'])} 元触及"
                   + '、'.join(STOP_NAMES.get(k, k) for k in x['breached']) + f"（{x['from']}–{x['to']}），程序没有补单")
    if q['minutes']['PRIMARY_DOWN'] >= 30:
        out.append(f"主行情接口累计 {q['minutes']['PRIMARY_DOWN']} 分钟没有给出可用报价")
    for key, e in (d.get('extras_errors') or {}).items():
        out.append(f"{'行情中断记录' if key == 'quote_health' else '通知与答复'}没有同步到本机：{e.get('error', '')}")
    g = d['governance']
    strategy_changes = list(dict.fromkeys(x['key'] for x in g['config_changes'] if x.get('class') == 'STRATEGY'))
    if strategy_changes:
        out.append('策略类设置被修改：' + '、'.join(strategy_changes))
    if g['issues_new']:
        out.append(f"新增工程问题 {len(g['issues_new'])} 条")
    return out


# Neutral values used when a section cannot be built; the page then says so instead of implying nothing happened.
EMPTY = {'availability': {'spans': [], 'offline_minutes': 0, 'paused_minutes': 0, 'away_minutes': 0},
         'jobs': {'by_kind': {}, 'longest_minutes': {}, 'failed': [], 'offline_stopped': [], 'long_cycles': [], 'reconnect_recoveries': 0},
         'collection': {'attempts': 0, 'failed': 0, 'network_errors': 0, 'attempts_offline': 0, 'failed_offline': 0, 'top_failures': [], 'new_documents': {}},
         'research': {'model_studies': {}, 'renewed': 0, 'studies_offline': 0, 'unsuccessful_offline': 0, 'analysis_failures': 0,
                      'analysis_failures_offline': 0, 'models': {}, 'stocks': [], 'global': [], 'dynamic_new_cases': {}},
         'portfolio': {'runs': {}, 'decisions_made': 0, 'latest_at': None, 'jobs': {}, 'job_failure_reasons': {}, 'longest_gap': None,
                       'longest_online_gap': None, 'latest_actions': {}, 'latest_target_bps': 0, 'latest_summary': '',
                       'changes': [], 'publications': {}, 'publication_bytes': {'max': None, 'last': None}, 'longest_gap_hours': None},
         'execution': {'fills': {}, 'orders_created': {}, 'equity_start_cents': None, 'equity_end_cents': None, 'cash_end_cents': None,
                       'marked_at': None, 'positions': [], 'risk': {}},
         'quotes': {'events': [], 'minutes': {'PRIMARY_DOWN': 0, 'NO_QUOTE': 0}, 'held_minutes': 0, 'breaches': [], 'exits_missed': [],
                    'check_errors': 0, 'open': 0},
         'review': {'status': 'NONE'},
         'governance': {'config_changes': [], 'proposals_new': [], 'proposals_decided': [], 'guidance_changes': [], 'issues_new': [],
                        'issues_recurring': 0, 'issues_resolved': [], 'issues_retitled': [], 'new_builds': [], 'agent_notes': []}}
SECTION_TITLES = {'availability': '本机在线', 'jobs': '任务运行', 'collection': '抓取', 'research': '研究', 'portfolio': '组合策略',
                  'execution': '云端执行', 'quotes': '行情源', 'review': '复盘', 'governance': '调整与治理'}
STOP_NAMES = {'cost_stop_cents': '成本止损价', 'plan_stop_cents': '计划止损价'}
QUOTE_EVENT_NAMES = {'PRIMARY_DOWN': '主接口没有可用报价', 'NO_QUOTE': '两个接口都没有可用报价'}


def _safe(name, fn):
    try:
        return fn()
    except Exception as exc:
        return {**copy.deepcopy(EMPTY[name]), 'error': f'{type(exc).__name__}: {str(exc)[:160]}'}


def build(store, config, day):
    a, b = day_window(day)
    today = local(now()).date().isoformat() == day
    from . import __version__
    from .build import info
    d = {'day': day, 'generated_at': normalize_time(now()), 'window': {'from': a, 'to': b}, 'version': __version__,
         'build_id': info(config, store)['build_id']}
    d['availability'] = _safe('availability', lambda: availability(store, a, b))
    spans = d['availability']['spans']
    for name, fn in (('jobs', lambda: jobs(store, a, b)), ('collection', lambda: collection(store, a, b, spans)),
                     ('research', lambda: research(store, config, a, b, spans)), ('portfolio', lambda: portfolio(store, a, b)),
                     ('execution', lambda: execution(store, config, a, b)), ('quotes', lambda: quotes(store, a, b)),
                     ('review', lambda: review(store, a, b)),
                     ('governance', lambda: governance(store, a, b))):
        d[name] = _safe(name, fn)
    d['research']['model_studies'] = dict(d['research']['model_studies'])
    try:
        d['extras_errors'] = extras_errors(store)
    except Exception:
        d['extras_errors'] = {}
    d['flags'] = [f'日报的“{SECTION_TITLES[n]}”一节生成失败：{d[n]["error"]}' for n in SECTION_TITLES if d[n].get('error')]
    try:
        d['flags'] += flags(d, config, today)
    except Exception as exc:
        d['flags'].append(f'异常规则检查失败：{type(exc).__name__}: {str(exc)[:160]}')
    return d


def _failed(section):
    return [f"- 本节生成失败（{section['error']}），下列数值为空，不代表当天没有发生。", ''] if section.get('error') else []


def _job_names():
    from .followups import JOB_NAMES
    return {**JOB_NAMES, **JOB_KIND_NAMES}


def markdown(d):
    names = _job_names()
    b = d['window']['to']
    L = [f"# 运行日报 {d['day']}（北京时间）", '',
         f"程序根据原始记录生成，不含模型判断。版本 {d['version']}，build {d['build_id']}，生成于 {local(d['generated_at']).strftime('%m-%d %H:%M')}。", '',
         '## 需要关注', '']
    L += [f'- {f}' for f in d['flags']] or ['- 无。']
    v = d['availability']
    L += ['', '## 本机在线', ''] + _failed(v)
    offline = [s for s in v['spans'] if s['kind'] == 'offline']
    paused = [s for s in v['spans'] if s['kind'] == 'pause']
    if offline:
        L.append(f"- 断网 {len(offline)} 次，共 {_hours(v['offline_minutes'])} 小时：" + '、'.join(_span(s, b) for s in offline) + '。')
    if paused:
        L.append(f"- 停顿 {len(paused)} 次，共 {_hours(v['paused_minutes'])} 小时（电脑睡眠或服务停止）：" + '、'.join(_span(s, b) for s in paused) + '。')
    stopped = Counter(names.get(j['kind'], j['kind']) for j in d['jobs'].get('offline_stopped') or [])
    if stopped:
        L.append('- 断网时停止、联网后重做的任务：' + '、'.join(f'{k} {n}' for k, n in stopped.items()) + '。')
    if not offline and not paused:
        L.append('- 没有断网或停顿记录。')
    c = d['collection']
    L += ['', '## 抓取', ''] + _failed(c) + [f"- 采集尝试 {c['attempts']} 次，失败 {c['failed']} 次" + (f"（网络类错误 {c['network_errors']} 次）" if c['network_errors'] else '')
                                              + (f"；其中离线或停顿期间尝试 {c['attempts_offline']} 次、失败 {c['failed_offline']} 次" if c['attempts_offline'] else '') + '。']
    if c['top_failures']:
        L.append('- 联网期间失败最多：' + '、'.join(f"{x['name']} {x['count']}" for x in c['top_failures']) + '。')
    L.append('- 新入库资料：' + _counts(dict(sorted(c['new_documents'].items())), DOCUMENT_NAMES) + '。')
    r = d['research']
    studies = r['model_studies']
    L += ['', '## 研究', ''] + _failed(r) + [f"- 模型研究 {sum(studies.values())} 次（成功 {studies.get('SUCCEEDED', 0)}），资料未变沿用结论 {r['renewed']} 次，研究生成失败 {r['analysis_failures']} 次"
          + (f"（其中离线期间 {r['analysis_failures_offline']} 次）" if r['analysis_failures_offline'] else '') + '。'
          + (' 当前计划所用模型：' + '、'.join(f'{m}（{n} 只）' for m, n in r['models'].items()) + '。' if r['models'] else ''), '',
          '| 股票 | 研究结论 | 计划 | 主要限制 | 来源 | 较前日 |', '|---|---|---|---|---|---|']
    for s in r['stocks']:
        L.append(f"| {s['name']} | {RESEARCH_NAMES.get(s['research'], s['research'] or '—')} | {PLAN_NAMES.get(s['plan'], s['plan'] or '—')} | "
                 f"{s['blockers']} | {s['source']} | {'变化' if s['changed'] else '—'} |")
    if r['global']:
        L += ['', '- 全球资产：' + '；'.join(f"{g['symbol']} {STANCE_NAMES.get(g['stance'], g['stance'] or '—')}、{PLAN_NAMES.get(g['plan'], g['plan'] or '—')}"
                                            + ('' if g['updated'] else '（当天未更新）') for g in r['global']) + '。']
    if r['dynamic_new_cases']:
        L.append('- 新闻发现的新候选：' + '、'.join(f'{k} {v}' for k, v in r['dynamic_new_cases'].items()) + '。')
    p = d['portfolio']
    gap = p.get('longest_gap')
    L += ['', '## 组合策略', ''] + _failed(p) + [f"- 组合决策运行 {sum(p['runs'].values())} 次（{_counts(p['runs'])}）；组合决策任务：{_counts(p['jobs'])}"
          + (f"（失败原因：{'、'.join(f'{k} {n}' for k, n in p['job_failure_reasons'].items())}）" if p['job_failure_reasons'] else '') + '。',
          f"- 发布到云端：{_counts(p['publications'])}"
          + (f"；最长间隔 {gap['hours']} 小时（{_md(gap['from'])} 至 {_md(gap['to'])}" + (f"，其中离线或停顿 {gap['away_hours']} 小时" if gap['away_hours'] else '') + '）' if gap else '') + '。']
    if p['publication_bytes']['last']:
        L.append(f"- 策略包大小：最后一次 {p['publication_bytes']['last'] / 1e6:.1f} MB，最大 {p['publication_bytes']['max'] / 1e6:.1f} MB。")
    if p['latest_at']:
        L.append(f"- 最新决策（{_md(p['latest_at'])}）：" + '、'.join(f"{ACTION_NAMES.get(k, k)} {v}" for k, v in p['latest_actions'].items())
                 + f"；目标总仓位 {p['latest_target_bps'] / 100:.1f}%。")
        L.append('- 与前一日最后决策相比：' + ('；'.join(f"{x['name']} {ACTION_NAMES.get(x['from'], x['from'])}→{ACTION_NAMES.get(x['to'], x['to'])}"
                                                   + (f"（目标 {(x['from_bps'] or 0) / 100:.1f}%→{(x['to_bps'] or 0) / 100:.1f}%）" if x['from_bps'] != x['to_bps'] else '')
                                                   for x in p['changes']) or '无变化') + '。')
        if p['latest_summary']:
            L.append(f"- 决策摘要：{p['latest_summary']}")
    e = d['execution']
    L += ['', '## 云端执行', ''] + _failed(e)
    if e['fills']:
        L += [f"- {route}：买入成交 {f['buy']} 笔、卖出 {f['sell']} 笔，已实现 {_yuan(f['realized_cents'])} 元（{'、'.join(f['symbols'])}）。" for route, f in e['fills'].items()]
    else:
        L.append('- 当天没有成交。')
    for x in e.get('dividends', []):
        L.append(f"- 分红入账：{x['name']} {x['qty']} 股 × 每股 {x['cash_per_share']} 元 = {_yuan(x['amount_cents'])} 元（税前，除息日 {x['ex_date']}）。")
    if e['equity_end_cents'] is not None:
        change = '' if e['equity_start_cents'] is None else f"，较前一日 {(e['equity_end_cents'] - e['equity_start_cents']) / 100:+,.2f} 元"
        L.append(f"- 净值 {_yuan(e['equity_end_cents'])} 元{change}；现金 {_yuan(e['cash_end_cents'])} 元（估值于 {_hm(e['marked_at'])}）。")
    if e['positions']:
        L.append('- 持仓：' + '、'.join(f"{x['name']} {x['weight_pct']}%" for x in e['positions']) + '。')
    if e['risk']:
        L.append('- 风控：' + json.dumps(e['risk'], ensure_ascii=False))
    q = d['quotes']
    L += ['', '## 行情源', ''] + _failed(q)
    if q['events']:
        L.append(f"- 主接口没有可用报价 {q['minutes']['PRIMARY_DOWN']} 分钟，两个接口都没有可用报价 {q['minutes']['NO_QUOTE']} 分钟"
                 + (f"（其中涉及持仓 {q['held_minutes']} 分钟）" if q['held_minutes'] else '') + '。')
        L.append('- 中断：' + '；'.join(f"{_hm(x['started_at'])}–{_hm(x['ended_at']) if x['ended_at'] else '进行中'} {QUOTE_EVENT_NAMES.get(x['kind'], x['kind'])}"
                                         f"（{x['symbols']} 只{'，持仓 ' + '、'.join(x['held']) if x['held'] else ''}）" for x in q['events'][:12])
                 + (f"；另有 {len(q['events']) - 12} 次" if len(q['events']) > 12 else '') + '。')
        checked = [x for x in q['breaches']] + [x for x in q['exits_missed']]
        if checked or q['check_errors']:
            L.append('- 中断期间按分时补查：' + ('；'.join(
                [f"{x['symbol']} 最低 {_yuan(x['low_cents'])} 元触及" + '、'.join(STOP_NAMES.get(k, k) for k in x['breached']) + f"（{x['from']}–{x['to']}）" for x in q['breaches']]
                + [f"{x['symbol']} 最高 {_yuan(x['high_cents'])} 元到过计划退出价（{x['from']}–{x['to']}）" for x in q['exits_missed']]) or '没有触及止损或退出价')
                     + (f"；{q['check_errors']} 只无法补查" if q['check_errors'] else '') + '。程序只记录，不补单。')
    else:
        L.append('- 没有行情中断记录。')
    v = d['review']
    L += ['', '## 复盘', ''] + _failed(v)
    if v['status'] == 'NONE':
        L.append('- 当天没有复盘记录。')
    else:
        L.append(f"- {_hm(v['window_end'])} 窗口复盘：{STATUS_NAMES.get(v['status'], v['status'])}；程序检查 {v['checks_passed']}/{v['checks_total']} 通过"
                 + f"，{v.get('checks_not_applicable', 0)} 项不适用"
                 + (f"（未通过：{'、'.join(CHECK_NAMES.get(c, c) for c in v['checks_failed'])}）" if v['checks_failed'] else '') + '；发现去向：'
                 + ('、'.join(f"{'工程问题' if k == 'engineering_issue' else '提案草稿' if k == 'proposal_draft' else k} {n}" for k, n in v['routing'].items()) or '无') + '。')
        if v['summary']:
            L.append(f"- 结论：{v['summary']}")
    g = d['governance']
    L += ['', '## 调整与治理', ''] + _failed(g)
    if g.get('selfcheck'):
        sc = g['selfcheck']
        L.append(f"- 长期自检：{sc.get('at')}；报告 {sc.get('report')}；仅生成待验证方案，未运行候选实验。")
    L += [f"- 设置修改：{x['key']} {json.dumps(x['before'], ensure_ascii=False)}→{json.dumps(x['after'], ensure_ascii=False)}（{x['class']}，"
          + (f"批准人 {x['approved_by']}，" if x.get('approved_by') else '') + f"理由：{(x.get('reason') or '')[:60]}）" for x in g['config_changes']] or ['- 设置：无修改。']
    L.append(f"- 提案：新建 {len(g['proposals_new'])}，决策 {len(g['proposals_decided'])}"
             + ('（' + '；'.join(f"{x['id']} {x['title']} → {_decision(x)}" for x in g['proposals_decided']) + '）' if g['proposals_decided'] else '') + '。')
    if g['guidance_changes']:
        L.append('- 研究规则变化：' + '；'.join(f"{x['id']} {x['status']}（{x['approved_by']}）" for x in g['guidance_changes']) + '。')
    L.append(f"- 工程问题：新增 {len(g['issues_new'])}，再次出现 {g['issues_recurring']}，关闭 {len(g['issues_resolved'])}"
             + ('（新增：' + '；'.join(f"{x['title']}" for x in g['issues_new'][:5]) + '）' if g['issues_new'] else '') + '。')
    if g.get('issues_retitled'):
        L.append('- 工程问题改标题：' + '；'.join(f"{x['id']}「{x['from']}」→「{x['to']}」" for x in g['issues_retitled']) + '。')
    if g['new_builds']:
        L.append('- 新版本号：' + '、'.join(filter(None, g['new_builds'])) + '。')
    if g['agent_notes']:
        L.append('- 桌面 agent 笔记：' + '、'.join(g['agent_notes']) + '。')
    j = d['jobs']
    L += ['', '## 任务运行', ''] + _failed(j) + ['| 任务 | 结果 | 最长耗时（分钟） |', '|---|---|---|']
    L += [f"| {names.get(k, k)} | {_counts(v)} | {j['longest_minutes'].get(k, '—')} |" for k, v in j['by_kind'].items()] or ['| — | 当天没有任务记录 | — |']
    return '\n'.join(L) + '\n'


def write(store, config, day=None):
    day = day or local(now()).date().isoformat()
    d = build(store, config, day)
    folder = store.root / 'workflow' / 'digests'
    json_write(folder / (day + '.json'), d)
    (folder / (day + '.md')).write_text(markdown(d), encoding='utf-8')
    return {'status': 'SUCCEEDED', 'day': day, 'report': str((folder / (day + '.md')).relative_to(store.root)), 'flags': d['flags']}


def rollup(store, config, since, until=None, folder=None, stem=None):
    """One page over several days for a supervisor's periodic check (evaluation batches write it into
    their own folder)."""
    until = until or local(now()).date().isoformat()
    start, finish = datetime.fromisoformat(since).date(), datetime.fromisoformat(until).date()
    if finish < start:
        raise ValueError('结束日期早于开始日期')
    if (finish - start).days > 62:
        raise ValueError('汇总区间最长 62 天')
    days = []
    cursor = start
    while cursor <= finish:
        days.append(build(store, config, cursor.isoformat()))
        cursor += timedelta(days=1)
    L = [f'# 运行汇总 {since} 至 {until}（北京时间）', '', '程序根据原始记录生成，不含模型判断；每天的明细见 workflow/digests/<日期>.md。', '',
         '## 逐日概况', '', '“离线 / 停顿”是本机断网和调度停止（睡眠或服务停止）的小时数；“最长间隔”括号里是其中离线或停顿的小时数。', '',
         '| 日期 | 离线 / 停顿 | 抓取失败 | 模型研究 / 沿用 / 失败 | 组合发布 / 最长间隔 | 成交笔数 | 净值（元） | 复盘 | 需关注 |', '|---|---|---|---|---|---|---|---|---|']
    for d in days:
        r, p, e, v = d['research'], d['portfolio'], d['execution'], d['availability']
        trades = sum(f['buy'] + f['sell'] for f in e['fills'].values())
        gap = p.get('longest_gap')
        away = f"{_hours(v['offline_minutes'])}h / {_hours(v['paused_minutes'])}h" if v['offline_minutes'] or v['paused_minutes'] else '—'
        interval = (f"{gap['hours']}h" + (f"（{gap['away_hours']}h）" if gap['away_hours'] else '')) if gap else '—'
        L.append(f"| {d['day']} | {away} | {d['collection']['failed']}/{d['collection']['attempts']} | {sum(r['model_studies'].values())} / {r['renewed']} / {r['analysis_failures']} | "
                 f"{p['publications'].get('SENT', 0)} / {interval} | {trades} | {_yuan(e['equity_end_cents'])} | "
                 f"{STATUS_NAMES.get(d['review']['status'], d['review']['status'])} | {len(d['flags'])} |")
    L += ['', '## 需要关注（按日期）', '']
    L += [f"- {d['day']}：{f}" for d in days for f in d['flags']] or ['- 无。']
    L += ['', '## 调整与治理', '']
    events = []
    for d in days:
        g = d['governance']
        events += [f"- {d['day']} 设置 {x['key']}：{json.dumps(x['before'], ensure_ascii=False)}→{json.dumps(x['after'], ensure_ascii=False)}（{x['class']}，{x.get('approved_by') or '运行类'}）" for x in g['config_changes']]
        events += [f"- {d['day']} 新提案 {x['id']}：{x['title']}（{x['status']}）" for x in g['proposals_new']]
        events += [f"- {d['day']} 提案决策 {x['id']}：{x['title']} → {_decision(x)}" for x in g['proposals_decided']]
        events += [f"- {d['day']} 研究规则 {x['id']} {x['status']}" for x in g['guidance_changes']]
        events += [f"- {d['day']} 新工程问题：{x['title']}" for x in g['issues_new']]
        events += [f"- {d['day']} 工程问题改标题 {x['id']}：「{x['from']}」→「{x['to']}」" for x in g.get('issues_retitled', [])]
    L += events or ['- 区间内没有设置、提案、研究规则或工程问题的变化。']
    last = days[-1]
    changed = [s['name'] for d in days for s in d['research']['stocks'] if s['changed']]
    L += ['', '## 期末状态', '', f"- 研究结论有变化的股票：{'、'.join(dict.fromkeys(changed)) or '无'}。"]
    if last['portfolio']['latest_at']:
        L.append('- 最新组合决策：' + '、'.join(f"{ACTION_NAMES.get(k, k)} {v}" for k, v in last['portfolio']['latest_actions'].items())
                 + f"；目标总仓位 {last['portfolio']['latest_target_bps'] / 100:.1f}%。")
    if last['execution']['positions']:
        L.append('- 持仓：' + '、'.join(f"{x['name']} {x['weight_pct']}%" for x in last['execution']['positions']) + '。')
    text = '\n'.join(L) + '\n'
    folder = folder or store.root / 'workflow' / 'digests'
    stem = stem or f'rollup-{since}_{until}'
    json_write(folder / (stem + '.json'), {'since': since, 'until': until, 'days': days})
    (folder / (stem + '.md')).write_text(text, encoding='utf-8')
    return {'status': 'SUCCEEDED', 'report': str((folder / (stem + '.md')).relative_to(store.root)), 'days': len(days),
            'flags': sum(len(d['flags']) for d in days)}
