"use strict";
const $=id=>document.getElementById(id);
const next=new URLSearchParams(location.search).get('next')||'/';
const destination=/^(\/|\/stocks\/(sh|sz)\d{6}|\/admin\/(settings|feedback))$/.test(next)?next:'/';
function message(text,error=false){$('login-feedback').textContent=text;$('login-feedback').hidden=!text;$('login-feedback').className='feedback'+(error?' error':'');}
async function session(){const r=await fetch('/api/session',{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw Error('无法读取登录状态，请刷新页面。');return r.json();}
async function start(){try{const s=await session();if(s.authenticated){location.replace(destination);return;}$('setup-form').hidden=!s.setup_required;$('login-form').hidden=s.setup_required;$('login-title').textContent=s.setup_required?'首次设置':'登录工作台';$('login-hint').textContent=s.setup_required?'为两个共享账号设置不同密码。Admin 可管理工作台；Guest 可查看研究并提交意见。':'选择账号并输入对应密码。';}catch(e){message(e.message,true);}}
async function send(path,body){const s=await session();const r=await fetch(path,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf_token},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(v.error||'操作未完成');return v;}
for(const id of ['login-form','setup-form'])$(id).addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;message('正在处理…');try{if(id==='setup-form'){if($('admin-password').value!==$('admin-confirm').value||$('guest-password').value!==$('guest-confirm').value)throw Error('两次输入的密码不一致。');await send('/api/setup',{admin_password:$('admin-password').value,guest_password:$('guest-password').value});$('setup-form').reset();await start();message('设置完成，请选择账号登录。');}else{await send('/api/login',{username:$('username').value,password:$('password').value});$('password').value='';location.assign(destination.startsWith('/admin/')&&$('username').value==='guest'?'/':destination);}}catch(e){message(e.message||'无法连接服务，请稍后重试。',true);}finally{b.disabled=false;}});
start();
